version: '3.9'

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    restart: always
    build: nginx
    tty: true
    networks:
      front:
    ports:
      - "443:443"
    volumes:
      - www:/var/www/html

  mariadb:
    env_file:
      - .env
    container_name: mariadb
    restart: always
    build: mariadb
    networks:
      back:
    volumes:
      - db:/var/lib/mysql

  wordpress:
    depends_on:
      - mariadb
    env_file:
      - .env
    container_name: wordpress
    restart: always
    build: wordpress
    networks:
      front:
      back:
    volumes:
      - www:/var/www/html

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/msegrans
    name: db
  www:
    driver_opts:
      type: none
      o: bind
      device: /home/msegrans
    name: www

networks:
  front:
  back:
