version: '3.9'

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    restart: always
    build: nginx
    tty: true
    networks:
      front:
    ports:
      - "443:443"
    volumes:
      - www:/var/www/html/wordpress
  mariadb:
    env_file:
      - .env
    container_name: mariadb
    restart: always
    build: mariadb
    networks:
      back:
    volumes:
      - db:/var/lib/mysql
  wordpress:
    depends_on:
      - mariadb
    env_file:
      - .env
    container_name: wordpress
    restart: always
    build: wordpress
    networks:
      front:
      back:
    volumes:
      - www:/var/www/html/wordpress

volumes:
  db:
    name: db
  www:
    name: www

networks:
  front:
  back:
